language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --prefer-dist --dev

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
